### ISSUE TITLE
No changes in Source code

### ISSUE THREAD

**Issue by mirogl** [thongtech/go-windows-arm#1]
Hi, I just wonder, why there are no changes in the source code to the official go source code. Did you use only a cross compiler and used the official source go ?  Or are any source changes needed to compile it for arm64 ?

Also it seems, that the binary ist only build for arm32 - not arm64:

$ file go.exe
go.ex_: PE32 executable (console) ARMv7 Thumb (stripped to external PDB), for MS Windows
An arm64 binary built using MSVC:

$ file TestARM64.exe
TestARM64.exe: PE32+ executable (GUI) Aarch64, for MS Windows

So - do you have any instructions, how to build go for arm64 ?

**Comment by thongtech** [comment]
Hi miragl,
I just noticed that it is exactly ARM32 binary, not ARM64, sorry for the misunderstanding and thanks for pointing that, I have updated the repo.
I only used the cross compiler with the official go 1.15.2 source with zero changes.
I have not figured out how to compile it for ARM64 either.
Best,
thongtech

**Comment by mirogl** [comment]
Hi @thongtech ,
Thanks - can you please give a short info which cross compiler with which options were used ?
Thanks
Miro

**Comment by thongtech** [comment]
Hi mirogl,

Sure, I used the method #2 from [Compile Golang (arm64) on a Windows (arm64) machine](https://medium.com/@tux0010/compile-golang-for-arm64-on-an-arm64-machine-7a86c133430e)
In short it would be:
- Set up an Ubuntu WSL on ARM machine (which will be Ubuntu arm64)
- On WSL, grab and install Go binary for **linux-arm64** from [https://golang.org/dl/](https://golang.org/dl/), also the Go source code
- Extract the source code archive then:
`cd go/src`
`export GOOS=windows`
`export GOARCH=arm`
`export GOARM=7`
`export CGO_ENABLED=0`
`./make.bash`
- The compiled binary will be in _go/bin/windows_arm_, move it out to _go/bin_
- Copy the whole _go_ folder out from the WSL to _C:\Go_ on the host
- That's it!

Best,
thongtech

**Comment by mirogl** [comment]
Hi @thongtech,
thanks - it didn't work for me, since I fot the error:
Building Go cmd/dist using /home/<my Username>/go/bootstrap. ()
ERROR: Cannot find /home/<my Username>/go/bootstrap/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.

I had to copy my /home/<my Username>/go directory content to /go/bootstrap - then it worked.
I could build a arm32 binary - the arm64 binary didn't work, since the build run on an error:

`/go/src$ ./make.bash
cmd/go: unsupported GOOS/GOARCH pair windows/arm64
Building Go cmd/dist using /home/miro/bootstrap/. ()
Building Go toolchain1 using /home/miro/bootstrap/.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for host, linux/arm64.
Building packages and commands for target, windows/arm64.
cmd/go: unsupported GOOS/GOARCH pair windows/arm64
go tool dist: FAILED: /home/<my Username>/go/pkg/tool/linux_arm64/go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 2`

But arm32 is better than win32 - many thanks
Miro

**Comment by thongtech** [comment]
Hi mirogl,

Glad to hear that arm32 binary finally works. However, it is still not possible for arm64 for now.
I haven't seen windows/arm64 assembly in the source yet, unlike windows/arm, which makes it possible.
And, I agree, arm32 binary is much better than the x86 one which runs painfully slow on my Surface Pro X.

As ARM PCs are rolling out, hopefully we will see the progress on windows/arm64 from go team soon!

Best,
thongtech
